server:
  port: 8080

spring:
  application:
    name: backend-temp

  datasource:
    url: jdbc:postgresql://localhost:5432/temp
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mySuperSecretKey12345678901234567890
  expiration: 86400000
